spring.application.name=spsw

# H2 Database
spring.datasource.url=jdbc:h2:mem:spswdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esto define las rutas donde vivira la documentacion Swagger

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api/grupo 1